---
rounds_idx: 0
model_tasks_idx: 1
reference_date_col_name: 'reference_date'
target_date_col_name: 'target_end_date'
horizon_col_name: 'horizon'
initial_checked_models: ['UMass-flusion', 'UMass-trends_ensemble']
disclaimer: "This is a disclaimer. It presents important information for your stakeholders."
